---
- name: Add proxy in /etc/environment
  become: yes
  blockinfile:
    path: /etc/environment
    block:  |
      HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      http_proxy=http://wwwproxy.unimelb.edu.au:8000/
      https_proxy=http://wwwproxy.unimelb.edu.au:8000/
      no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au

#  pip install --upgrade pip
- name: Install dependencies
  tags: always
  become: yes
  apt:
    name: ['apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'software-properties-common', 'unzip', 'vim']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Setup config for web
  shell:  |
    sudo rm /var/lib/apt/lists/lock
    sudo rm /var/cache/apt/archives/lock
    sudo rm /var/lib/dpkg/lock*
    sudo dpkg --configure -a

- name: install couchdb web packages and source
  shell:  |
    sudo apt-get update
    sudo apt-get inatall -y python3-pip
    sudo apt-get inatall -y npm
    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    
- name: install more web dependencies
  shell:  |
    sudo apt-get install -y nodejs
    sudo apt-get install -y node-grunt-cli
    sudo apt-get install -y jq
    sudo apt-get install -y qgis
    sudo apt-get install -y git    
    git clone https://github.com/AURIN/comp90024.git
    npm install ./comp90024
